import { ChildProfile, ChurchEventNotification } from '../../types';

export const mockChildrenProfiles: ChildProfile[] = [
  {
    id: 'c1',
    nameEn: 'Mina Emad',
    nameAr: 'مينا عماد',
    age: 9,
    gradeEn: '4th Grade Elementary',
    gradeAr: 'الصف الرابع الابتدائي',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MinaEmad&backgroundColor=b6e3f4',
    points: 950,
    rank: 2,
    attendanceRate: 96,
    screenTimeMinutes: 115,
    completedLessonsCount: 7,
    totalLessonsCount: 9,
    verseMemorizedCount: 6,
    pendingRewardsCount: 1,
    lessons: [
      {
        lessonId: 'l1',
        lessonTitleEn: 'The Story of St. Mina the Wonder-Worker',
        lessonTitleAr: 'قصة الشهيد العظيم مارمينا العجائبي',
        category: 'church_history',
        dateCompleted: '2026-09-14',
        status: 'completed',
        quizScore: { correct: 3, total: 3 },
        pointsEarned: 150,
        pointsMax: 150,
        memoryVerseEn: '"I can do all things through Christ who strengthens me." (Philippians 4:13)',
        memoryVerseAr: '«أَسْتَطِيعُ كُلَّ شَيْءٍ فِي الْمَسِيحِ الَّذِي يُقَوِّينِي» (فيلبي ٤: ١٣)',
        teacherNoteEn: 'Mina showed exceptional understanding of St. Mina’s courage and chanted the doxology with great reverance!',
        teacherNoteAr: 'أظهر مينا فهماً رائعاً لشجاعة مارمينا وشارك في ترتيل الذكصولوجية بخشوع جميل.'
      },
      {
        lessonId: 'l2',
        lessonTitleEn: 'Noah and the Ark of Salvation',
        lessonTitleAr: 'نوح وفلك النجاة وعهد الله',
        category: 'bible_stories',
        dateCompleted: '2026-09-08',
        status: 'completed',
        quizScore: { correct: 3, total: 3 },
        pointsEarned: 150,
        pointsMax: 150,
        memoryVerseEn: '"By faith Noah, being divinely warned of things not yet seen, moved with godly fear, prepared an ark." (Hebrews 11:7)',
        memoryVerseAr: '«بِالإِيمَانِ نُوحٌ لَمَّا أُوحِيَ إِلَيْهِ عَنْ أُمُورٍ لَمْ تُرَ بَعْدُ خَافَ، فَبَنَى فُلْكًا لِخَلاَصِ بَيْتِهِ» (عبرانيين ١١: ٧)',
        teacherNoteEn: 'Wrote an inspiring reflection on trusting God when obedience is difficult.',
        teacherNoteAr: 'كتب تأملاً مؤثراً عن الثقة في مواعيد الله حتى حينما تكون الطاعة صعبة.'
      },
      {
        lessonId: 'l3',
        lessonTitleEn: 'Coptic Hymns: Golgotha & Holy Week Rituals',
        lessonTitleAr: 'الألحان القبطية: لحن جولجوثا وطقس أسبوع الآلام',
        category: 'hymns_rituals',
        dateCompleted: '2026-08-30',
        status: 'completed',
        quizScore: { correct: 2, total: 3 },
        pointsEarned: 120,
        pointsMax: 150,
        memoryVerseEn: '"Sing praises to God, sing praises; sing praises to our King, sing praises!" (Psalm 47:6)',
        memoryVerseAr: '«رَنِّمُوا لِلَّهِ، رَنِّمُوا! رَنِّمُوا لِمَلِكِنَا، رَنِّمُوا!» (مزمور ٤٧: ٦)',
        teacherNoteEn: 'Mastered the first two phrases of the hymn in Coptic with deacon pronunciation.',
        teacherNoteAr: 'أتقن أول جملتين من اللحن باللفظ القبطي السليم مثل الشمامسة.'
      },
      {
        lessonId: 'l4',
        lessonTitleEn: 'David and Goliath: Courage in the Lord',
        lessonTitleAr: 'داود وجليات: النصرة بقوة رب الجنود',
        category: 'bible_stories',
        status: 'in_progress',
        pointsEarned: 75,
        pointsMax: 150,
        memoryVerseEn: '"The battle is the Lord’s, and He will give you into our hands." (1 Samuel 17:47)',
        memoryVerseAr: '«لأَنَّ الْحَرْبَ لِلرَّبِّ وَهُوَ يَدْفَعُكُمْ لِيَدِنَا» (١ صموئيل ١٧: ٤٧)',
        teacherNoteEn: 'Listened to audio explanation. Quiz and reflection pending submission.',
        teacherNoteAr: 'استمع للتسجيل الصوتي للشرح، ومتبقي تسليم الاختبار القصير والتأمل.'
      },
      {
        lessonId: 'l5',
        lessonTitleEn: 'The Agpeya: 3rd Hour & the Holy Spirit',
        lessonTitleAr: 'الأجبية المقدسة: صلاة الساعة الثالثة وعمل الروح القدس',
        category: 'ethics_prayers',
        status: 'assigned',
        pointsEarned: 0,
        pointsMax: 150,
        memoryVerseEn: '"Your Holy Spirit, O Lord, do not take from us." (Agpeya 3rd Hour)',
        memoryVerseAr: '«رُوحُكَ القُدُّوس يَا رَبَّنَا لاَ تَنْزِعْهُ مِنَّا» (صلاة الساعة الثالثة)',
        teacherNoteEn: 'Assigned for next Sunday’s class. Preparation audio available.',
        teacherNoteAr: 'مُحدد للأحد القادم. ملف الشرح متاح للاستماع مسبقاً.'
      }
    ]
  },
  {
    id: 'c2',
    nameEn: 'Mary Emad',
    nameAr: 'مريم عماد',
    age: 7,
    gradeEn: '2nd Grade Elementary',
    gradeAr: 'الصف الثاني الابتدائي',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MaryEmad&backgroundColor=ffd5dc',
    points: 820,
    rank: 1,
    attendanceRate: 100,
    screenTimeMinutes: 70,
    completedLessonsCount: 6,
    totalLessonsCount: 7,
    verseMemorizedCount: 5,
    pendingRewardsCount: 0,
    lessons: [
      {
        lessonId: 'l201',
        lessonTitleEn: 'The Nativity of the Lord Jesus Christ',
        lessonTitleAr: 'ميلاد ربنا ومخلصنا يسوع المسيح في المغارة',
        category: 'bible_stories',
        dateCompleted: '2026-09-12',
        status: 'completed',
        quizScore: { correct: 3, total: 3 },
        pointsEarned: 150,
        pointsMax: 150,
        memoryVerseEn: '"Glory to God in the highest, and on earth peace, goodwill toward men!" (Luke 2:14)',
        memoryVerseAr: '«الْمَجْدُ لِلَّهِ فِي الأَعَالِي، وَعَلَى الأَرْضِ السَّلاَمُ، وَبِالنَّاسِ الْمَسَرَّةُ» (لوقا ٢: ١٤)',
        teacherNoteEn: 'Mary memorized the Luke verse perfectly on her first attempt!',
        teacherNoteAr: 'حفظت مريم آية إنجيل لوقا بإتقان ممتاز من أول محاولة!'
      },
      {
        lessonId: 'l202',
        lessonTitleEn: 'The Good Samaritan: Helping with Love',
        lessonTitleAr: 'السامري الصالح: كيف نحب ونساعد الآخرين',
        category: 'ethics_prayers',
        dateCompleted: '2026-09-05',
        status: 'completed',
        quizScore: { correct: 3, total: 3 },
        pointsEarned: 150,
        pointsMax: 150,
        memoryVerseEn: '"You shall love your neighbor as yourself." (Mark 12:31)',
        memoryVerseAr: '«تُحِبُّ قَرِيبَكَ كَنَفْسِكَ» (مرقس ١٢: ٣١)',
        teacherNoteEn: 'Demonstrates kind-hearted leadership among her classmates.',
        teacherNoteAr: 'تتحلى بروح المحبة والتعاون الصادق مع زميلاتها في الفصل.'
      },
      {
        lessonId: 'l203',
        lessonTitleEn: 'Coptic Hymns: O Monogenis (Only-Begotten)',
        lessonTitleAr: 'الألحان القبطية: لحن أو مونوجينيس (الابن الوحيد)',
        category: 'hymns_rituals',
        dateCompleted: '2026-08-28',
        status: 'completed',
        quizScore: { correct: 3, total: 3 },
        pointsEarned: 150,
        pointsMax: 150,
        memoryVerseEn: '"For God so loved the world that He gave His only begotten Son." (John 3:16)',
        memoryVerseAr: '«لأَنَّهُ هكَذَا أَحَبَّ اللهُ الْعَالَمَ حَتَّى بَذَلَ ابْنَهُ الْوَحِيدَ» (يوحنا ٣: ١٦)',
        teacherNoteEn: 'Sweet singing voice, loves chanting church hymns at home.',
        teacherNoteAr: 'صوت جميل ومميز، تحب ترتيل ألحان الكنيسة دائماً.'
      },
      {
        lessonId: 'l204',
        lessonTitleEn: 'Queen Esther: Praying for Her People',
        lessonTitleAr: 'الملكة أستير: الشجاعة والصوم والصلاة',
        category: 'church_history',
        status: 'in_progress',
        pointsEarned: 60,
        pointsMax: 150,
        memoryVerseEn: '"And who knows whether you have not come to the kingdom for such a time as this?" (Esther 4:14)',
        memoryVerseAr: '«وَمَنْ يَعْلَمُ إِنْ كُنْتِ لِوَقْتٍ مِثْلِ هذَا وَصَلْتِ إِلَى المُلْكِ؟» (أستير ٤: ١٤)',
        teacherNoteEn: 'Read story slides, practicing the memorization verse.',
        teacherNoteAr: 'قرأت شرائح القصة، وتقوم حالياً بحفظ الآية الذهبية.'
      }
    ]
  }
];

export const mockChurchEventNotifications: ChurchEventNotification[] = [
  {
    id: 'ev-cross',
    titleEn: 'Feast of the Glorious Cross (Divine Liturgy & Procession)',
    titleAr: 'عيد الصليب المجيد (القداس الإلهي والدورة الطقسية)',
    category: 'liturgy',
    date: '2026-09-27',
    timeEn: '6:30 AM – 9:30 AM',
    timeAr: '٦:٣٠ ص – ٩:٣٠ ص',
    locationEn: 'St. Musa Cathedral - Main Sanctuary',
    locationAr: 'كاتدرائية القديس موسى - المذبح الرئيسي',
    descriptionEn: 'Celebration of the Holy Cross discovery. Deacons procession with basil and lit candles. Families and children are encouraged to attend in white deacons vestments.',
    descriptionAr: 'الاحتفال بظهور الصليب المقدس. زفة الشمامسة بأغصان الريحان والشموع المضيئة. ندعو الأطفال للبس التونية وحضور التناول المقدس.',
    priority: 'feast',
    isRead: false,
    isRsvp: true,
    rsvpCount: 142,
    hasReminder: true
  },
  {
    id: 'ev-trip',
    titleEn: 'Sunday School Autumn Retreat: St. Mina Monastery (Maryout)',
    titleAr: 'رحلة مدارس الأحد الخريفية: دير مارمينا العجائبي بمريوط',
    category: 'sunday_school',
    date: '2026-10-03',
    timeEn: '6:00 AM Departure – 8:30 PM Return',
    timeAr: 'التحرك ٦:٠٠ ص – العودة ٨:٣٠ م',
    locationEn: 'Church Main Gate (Air-Conditioned Buses)',
    locationAr: 'البوابة الرئيسية للكنيسة (أتوبيسات مكيفة)',
    descriptionEn: 'Spiritual day for kids and parents including liturgy at St. Mina Monastery, taking the blessing of Pope Kyrillos VI tomb, biblical games, and lunch.',
    descriptionAr: 'يوم روحي وترفيهي للأطفال وأولياء الأمور يشمل صلاة القداس بدير مارمينا، أخذ بركة مزار البابا كيرلس السادس، ومسابقات وفقرات كشفية.',
    priority: 'high',
    isRead: false,
    isRsvp: false,
    rsvpCount: 88,
    hasReminder: false
  },
  {
    id: 'ev-parents',
    titleEn: 'Parents & Servants Spiritual Fellowship: "Christian Parenting in the Digital Age"',
    titleAr: 'اجتماع أولياء الأمور والخدام: "تربية الأبناء المسيحيين في العصر الرقمي"',
    category: 'family',
    date: '2026-09-22',
    timeEn: '7:00 PM – 8:45 PM',
    timeAr: '٧:٠٠ م – ٨:٤٥ م',
    locationEn: 'St. Mark Auditorium (Ground Floor)',
    locationAr: 'قاعة القديس مرقس للمؤتمرات (الدور الأرضي)',
    descriptionEn: 'Special meeting with church priests and specialized educators discussing healthy screen time habits, digital spiritual safety, and open Q&A.',
    descriptionAr: 'لقاء روحي وتربوي خاص مع الآباء الكهنة ونخبة من التربويين لمناقشة أوقات الشاشة الآمنة والتربية النفسية السليمة مع فقرة أسئلة مفتوحة.',
    priority: 'high',
    isRead: true,
    isRsvp: true,
    rsvpCount: 65,
    hasReminder: true
  },
  {
    id: 'ev-hymn-fest',
    titleEn: 'Annual Coptic Hymns & Agpeya Festival Auditions',
    titleAr: 'مهرجان الألحان القبطية والأجبية السنوي: تصفيات المسابقة',
    category: 'hymn',
    date: '2026-10-10',
    timeEn: '4:00 PM – 7:30 PM',
    timeAr: '٤:٠٠ م – ٧:٣٠ م',
    locationEn: 'Sunday School Educational Building',
    locationAr: 'مبنى مدارس الأحد - مسرح الأنبا أنطونيوس',
    descriptionEn: 'Children showcase their mastered hymns (Golgotha, Khen Oushot, O Monogenis) and Agpeya prayers before the church cantors committee.',
    descriptionAr: 'تقديم الأطفال لألحانهم ومزامير الأجبية المحفوظة أمام لجنة الشمامسة والمعلمين لنيل أوسمة التفوق والشهادات التقديرية.',
    priority: 'normal',
    isRead: false,
    isRsvp: false,
    rsvpCount: 47,
    hasReminder: false
  },
  {
    id: 'ev-tasbeha',
    titleEn: 'Vespers & Family Midnight Praises (Tasbeha)',
    titleAr: 'عشية وتسبحة نصف الليل للعائلات والشباب',
    category: 'liturgy',
    date: '2026-09-26',
    timeEn: '6:30 PM Vespers | 7:30 PM Tasbeha',
    timeAr: '٦:٣٠ م العشية | ٧:٣٠ م التسبحة',
    locationEn: 'St. Athanasius Chapel',
    locationAr: 'كنيسة القديس أثناسيوس الرسولي',
    descriptionEn: 'Praising God with the 7 Psali, Theotokia, and hymns with cymbals and triangle. Great opportunity for kids to chant alongside church deacons.',
    descriptionAr: 'ترتيل التسبحة مع الشمامسة بالدف والمثلث (سبع طرائق وإبصاليات وثاوطوكيات). فرصة مميزة لتعليم الأطفال التسبيح والتأمل الروحي.',
    priority: 'normal',
    isRead: true,
    isRsvp: false,
    rsvpCount: 92,
    hasReminder: false
  }
];
